openapi: 3.0.0
info:
  version: 1.0.0
  title: Glow E-commerce Website
  description: API for Glow platform - skin care products 
  contact:
    email: 1nourahalmanea@gmail.com
servers:
  - url: http://localhost:8000
tags:
  - name: products
    description: Everything about your products

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string     
          
    Product:
     type: object
     required:
       - name
       - category
       - description
       - price
       - image
     properties:
       id:
         type: string
       name:
         type: string
       price:
         type: number
       description:
         type: string
       category:
         type: string
       image:
        type: string


paths:
  /products:
    get:
      summary: Get list of products
      responses:
        200:
          description: Return all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        500:
          description: Server error
  /products/{productId}:
    post:
      summary: Create a product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: Single product is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          description: Server error

    get:
      tags:
        - products
      summary: Get a single product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Single product is returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          description: Server error
    put:
      summary: Update a single product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Update a single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          description: Server error
    delete:
      summary: Delete a single product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        200:
          description: Delete a single product
        500:
          description: Server error
  /products/search:
    get:
      summary: Search products
      parameters:
        - in: query
          name: search
          required: true
          schema:
            type: string
      responses:
        200:
          description: All the products are returned based on the search value
          content:
            application/json:
              schema:
                type: array
                items:
                  description: All the products are returned based on the search value
                  $ref: '#/components/schemas/Product'
        500:
          description: Server error
        
     

                    
       
